name: Create Pull Request
on:
  push:
    branches: ['*', '!main']

jobs:
  pr:
    name: create pr on development branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create pull request
        uses: devops-infra/action-pull-request@v0.4.2
        id: cpr
        with:
          title: Actions Pull Request
          github_token: ${{ secrets.GH_PAT_TOKEN }}
          target_branch: development
          template: .github/PULL_REQUEST_TEMPLATE.md
          body: "**Automated pull request**"
      - name: Check outputs
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.url }}"
