name: TFSec
on:
  push:
    branches:
      - '*'
      - '!main'
      - '!development'
      - '!staging'

  pull_request:
    branches: [main,development,staging]
defaults:
  run:
    working-directory: ./environment

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path: [esg_se_xdr_demo_prod,nsg_amazon_playground,public_cloud_optix_demo]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          github_token: ${{ github.token }}
          tfsec_args: --no-module-downloads --soft-fail --out ./results
          working_directory: ${{ matrix.path }}
      - name: Put results in Env Var
        run: |
          RESULTS=$(cat ./results)
          echo "RESULTS<<EOF" >> $GITHUB_ENV
          echo "$RESULTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Post results to Github PR
        uses: mshick/add-pr-comment@v1
        with:
          allow-repeats: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]'
          message: |
            ${{ env.RESULTS }}
